
<?php
/**
 * @var $block ListPost
 */

use AHT\Blog\Block\ListPost;

 /** $block called form class defined in class name layout */
$posts = $block->getPosts();
?>

<?php if ($posts->getSize() > 0): ?>
    <table class="table table-bordered table-striped mt-5" border="1px">
        <tr style="text-align: center;">
            <th scope="col" style="text-align: center"><?= __("Post Name") ?></th>
            <th scope="col" style="text-align: center"><?= __("Image") ?></th>
            <th scope="col" style="text-align: center"><?= __("Short Description") ?></th>
        </tr>
        <?php foreach ($posts as $post): ?>
            <tr style="text-align: center">
                <td style="width: 120px"><a class="post_url" href="<?=$block->escapeUrl($block->getUrlPost($post->getId()))?>" ><?= $post->getName() ?></a></td>
                <td><img height="150px" width="100px" src="<?php echo $block->getImageUrl($post->getImage()) ?>" /></td>
                <td><?= $post->getShortDesc() ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
    <br>

    <?php if ($block->getPagerHtml()): ?>
        <div class="blog-posts-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else: ?>
<?php endif; ?>
